# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170627_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hardware_devices',
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(choices=[('VIC', 'Victoria'), ('ACT', 'Australian Capital Territory'), ('NSW', 'New South Wales'), ('QLD', 'Queensland'), ('WA', 'Western Australia'), ('SA', 'South Australia'), ('NT', 'Northern Territory'), ('TAS', 'Tasmania')], default='VIC', max_length=3),
        ),
    ]
