# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170630_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.IntegerField()),
                ('device', models.ManyToManyField(to='website.Hardware')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='programmingBackground',
            field=models.IntegerField(choices=[(1, 'I have never programmed before (e.g. Only touch a computer when required)'), (2, 'Some programming (e.g. I have written some programs to carry out simple tasks)'), (3, 'Experienced programmer (e.g. I have used programs for computation, automation)'), (4, 'Expert programmer (e.g. I have worked as a programmer before, contributedcode to large projects and/or coded for high level algorithmic computation)')], default='Expert'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='technologyBackground',
            field=models.IntegerField(choices=[(1, 'I never use technology (e.g. Only touch a computer when required)'), (2, 'Novice (e.g. Only use it to send emails and browse the internet)'), (3, 'Intermediate (e.g. Can confidently use technology most of the time without assistance)'), (4, 'Expert (e.g. Most of the time people come to you as the person to ask with their technology issues)')], default='Expert'),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Profile'),
        ),
    ]
