# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170630_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='device',
        ),
    ]
