# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_hardware_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='imageUrl',
            field=models.CharField(default='https://pixabay.com/photo-2123967/', max_length=300),
        ),
    ]
