# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20170704_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question10',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question11',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question12',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question2',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question3',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question4',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question5',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question6',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question7',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question8',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question9',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='imageUrl',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/f/f8/Question_mark_alternate.svg', max_length=300),
        ),
    ]
