# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20170705_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicequestionnaire',
            name='question1',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Strongly Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
    ]
