# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20170710_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicequestionnaire',
            name='question10',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Strongly Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AlterField(
            model_name='devicequestionnaire',
            name='question11',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Strongly Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AlterField(
            model_name='devicequestionnaire',
            name='question12',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Strongly Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AlterField(
            model_name='devicequestionnaire',
            name='question2',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Strongly Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AlterField(
            model_name='devicequestionnaire',
            name='question3',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Strongly Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AlterField(
            model_name='devicequestionnaire',
            name='question4',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Strongly Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AlterField(
            model_name='devicequestionnaire',
            name='question5',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Strongly Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AlterField(
            model_name='devicequestionnaire',
            name='question6',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Strongly Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AlterField(
            model_name='devicequestionnaire',
            name='question7',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Strongly Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AlterField(
            model_name='devicequestionnaire',
            name='question8',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Strongly Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AlterField(
            model_name='devicequestionnaire',
            name='question9',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Strongly Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
    ]
