# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20170712_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question13',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question14',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question15',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question16',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question17',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question18',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question19',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question20',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question21',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question22',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question23',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question24',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question25',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question26',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question27',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question28',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question29',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='question30',
            field=models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
    ]
