# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20170902_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('answer', models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question10',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question11',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question12',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question13',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question14',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question15',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question16',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question17',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question18',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question19',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question20',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question21',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question22',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question23',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question24',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question25',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question26',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question27',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question28',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question29',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question3',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question30',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question4',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question5',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question6',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question7',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question8',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question9',
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.DeviceQuestionnaire'),
        ),
    ]
