# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20170903_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Hardware')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='hardware',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question10',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question11',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question12',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question13',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question14',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question15',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question16',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question17',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question18',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question19',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question20',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question21',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question22',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question23',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question24',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question25',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question26',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question27',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question28',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question29',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question3',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question30',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question4',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question5',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question6',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question7',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question8',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='question9',
        ),
        migrations.RemoveField(
            model_name='devicequestionnaire',
            name='user',
        ),
        migrations.AddField(
            model_name='devicequestionnaire',
            name='name',
            field=models.CharField(default='hardware', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.DeviceQuestionnaire'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Profile'),
        ),
    ]
