# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20170903_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerIntegerField',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.Answer')),
                ('body', models.PositiveIntegerField(blank=True, null=True)),
            ],
            bases=('website.answer',),
        ),
        migrations.CreateModel(
            name='AnswerText',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.Answer')),
                ('body', models.TextField(blank=True, null=True)),
            ],
            bases=('website.answer',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.DeviceQuestionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Hardware')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.DeviceQuestionnaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='hardware',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'text'), ('radio', 'radio')], default='radio', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Category'),
        ),
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Response'),
        ),
    ]
