# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20170903_1257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceQuestionnaire',
            new_name='Questionnaire',
        ),
    ]
