# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20170903_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerRadio',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.Answer')),
                ('body', models.TextField(blank=True, null=True)),
            ],
            bases=('website.answer',),
        ),
        migrations.RemoveField(
            model_name='answerintegerfield',
            name='answer_ptr',
        ),
        migrations.DeleteModel(
            name='AnswerIntegerField',
        ),
    ]
