# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20170903_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='imageUrl',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/3/33/White_square_with_question_mark.png', max_length=300),
        ),
    ]
