# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20170905_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='programmingBackground',
            field=models.IntegerField(choices=[(1, 'I have never programmed before (e.g. Only touch a computer when required)'), (2, 'Some programming (e.g. I have written some programs to carry out simple tasks)'), (3, 'Experienced programmer (e.g. I have used programs for computation, automation)'), (4, 'Expert programmer (e.g. I have worked as a programmer before, contributed code to large projects and/or coded for high level algorithmic computation)')], default='Expert'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yearLevels',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', 'Prep'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Year 7'), ('8', 'Year 8'), ('9', 'Year 9'), ('10', 'Year 10'), ('11', 'Year 11'), ('12', 'Year 12')], max_length=28, null=True),
        ),
    ]
