# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 05:52
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20170908_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='yearLevels',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Prep'), (1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Year 7'), (8, 'Year 8'), (9, 'Year 9'), (10, 'Year 10'), (11, 'Year 11'), (12, 'Year 12')], max_length=28, null=True),
        ),
    ]
